import {
  FileText,
  Image,
  Video,
  Music,
  Camera,
  Folder,
  Palette,
  Sunrise,
  Film,
  Paintbrush,
  Save,
  FolderOpen,
  Users,
  Settings,
  BookOpen,
  Tag,
  Heart,
  Clock,
  Layout,
  Archive,
  Footprints,
  FileMusic,
  MessageSquare,
  Calendar,
  Globe,
  Sparkles,
  Moon,
  Star,
  Sun,
} from "lucide-vue-next";

export const groupIcons = [
  { name: "Folder", icon: Folder },
  { name: "Image", icon: Image },
  { name: "Palette", icon: Palette },
  { name: "Sunrise", icon: Sunrise },
  { name: "Film", icon: Film },
  { name: "Camera", icon: Camera },
  { name: "Video", icon: Video },
  { name: "Paintbrush", icon: Paintbrush },
  { name: "Save", icon: Save },
  { name: "FolderOpen", icon: FolderOpen },
];

export const moduleIcons: Record<string, any> = {
  article: FileText,
  gallery: Image,
  video: Video,
  music: FileMusic,
  lyric: FileMusic,
  scenes: Layout,
  memory: Heart,
  users: Users,
  logs: Clock,
  settings: Settings,
  audio: Music,
  footprint: Footprints,
};

export const pageIcons: Record<string, any> = {
  archive: Archive,
  categories: Tag,
  tags: Tag,
  lyrics: FileMusic,
  gallery: Image,
  scenes: Layout,
  about: BookOpen,
  footprint: Footprints,
};

export const categoryIcons = [
  { name: "Folder", icon: Folder },
  { name: "FileText", icon: FileText },
  { name: "Image", icon: Image },
  { name: "Music", icon: Music },
  { name: "Video", icon: Video },
  { name: "Palette", icon: Palette },
  { name: "Heart", icon: Heart },
  { name: "Tag", icon: Tag },
  { name: "Star", icon: Star },
  { name: "Sparkles", icon: Sparkles },
];

export const lyricCategoryIcons = [
  { name: "Folder", icon: Folder },
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "Music", icon: Music },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "BookOpen", icon: BookOpen },
  { name: "Calendar", icon: Calendar },
  { name: "Globe", icon: Globe },
];
